### ISSUE TITLE
Remove clj-time dep

### ISSUE THREAD

**Issue by bbatsov** [razum2um/clj-debugger#3]
We're looking into integrating clj-debugger with CIDER and it'd awesome it had no deps other than Clojure (as middleware deps can't be isolated from app deps). Are you ok with removing the clj-time dependency?

**Comment by Malabarba** [comment]
For reference: clojure-emacs/cider-nrepl#170

**Comment by bbatsov** [comment]
@Bruce-Connor you linked to the wrong project. :-)

**Comment by Malabarba** [comment]
@bbatsov Fixed :)

**Comment by razum2um** [comment]
@bbatsov @Bruce-Connor hi, I'm glad you interested in the project :)

my thoughts concerning clj-time: it's the second time people complain about dependencies (my aprint would be upstreamed into pprint if it wouldn't depend on anything) and this makes me upset.

I've also already expressed my concerns about "every project has it's own -utils jar which all shares nearly the same functionality, but there's nothing widespread like activesupport" in #irc, but nobody cares about sharing utility function. clojure-contrib also went down (which I partially agree with), but there appeared nothing more modular instead.

The analogy comes to my mind here, because inlining the deps-code is even worse imo :\
But I understand your worries about deps-leaking, let's discuss this.

1) Couldn't the issue be solved by `:exclusions [clj-time/clj-time]` ? 
2) It there anything similar to google-closure-compiler dead code elimination for clojure? (I mean it could be helpful to extract all the third-lib code and inline it into jar while packaging + hack the classloader like this: http://stackoverflow.com/questions/17775591/parent-last-classloader-to-solve-java-class-path-hell to be sure loading bundled deps) => provide groupId/artifactId-lib-standalone.jar while lein deploy
3) Would deploying lib's uberjar with corresponding name on clojars work?

**Comment by bbatsov** [comment]
> 1) Couldn't the issue be solved by :exclusions [clj-time/clj-time] ?

Too problematic for end users unfortunately - most of them simply won't realize what's causing such a problem. Every time we've added new deps to CIDER someone has complained about them.

> 2) It there anything similar to google-closure-compiler dead code elimination for clojure? (I mean it could be helpful to extract all the third-lib code and inline it into jar while packaging + hack the classloader like this: http://stackoverflow.com/questions/17775591/parent-last-classloader-to-solve-java-class-path-hell to be sure loading bundled deps) => provide groupId/artifactId-lib-standalone.jar while lein deploy

The best approach is usually source renaming. There are some tools to simplify this, e.g. [mranderson](https://github.com/benedekfazekas/mranderson). //cc @expez @benedekfazekas

If you devise a better way to do this - please do tell! :-)

I haven't looked at the code, but why is date manipulation needed in a debugger?

P.S. See the related discussion [here](https://github.com/clojure-emacs/refactor-nrepl/issues/20).

**Comment by benedekfazekas** [comment]
mranderson may be a bit of help here. see its readme for docs or a really short guide on usage can be found here: https://github.com/clojure-emacs/refactor-nrepl#development-with-mranderson

that said mranderson can only inline clj code for now, it does not handle java. as clj-time's transient dep is joda: mranderson won't help for users clashing on diff versions of joda. i don't know how big a problem is this. since joda is quite stable it might not be...

**Comment by expez** [comment]
Rewriting what little time related code is in this project using `java.util.Date` and friends is the way to go, I think.
